import React, { useState, useEffect } from "react";
import { useAuth } from "../../contexts/AuthContext";
import { useModal } from "../../contexts/ModalContext";
import ResponsiveSelect from "../../components/common/ResponsiveSelect";
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer } from "recharts";
import {
  RefreshCw, Info, AlertTriangle, CheckCircle, Search, Edit2,
  LayoutGrid, FileText, Download, CheckCircle2, ChevronDown,
  MapPin, Clock, Users, BookOpen, Plus, UserPlus, Home, AlertCircle, FileBarChart, Calendar
} from "lucide-react";

const EXAMSLOTS = [
  '09:00 AM - 12:00 PM',
  '02:00 PM - 05:00 PM'
];
const DATES = [
  '2026-07-13',
  '2026-07-14',
  '2026-07-15',
  '2026-07-16',
  '2026-07-17',
  '2026-07-20',
  '2026-07-21',
  '2026-07-22',
  '2026-07-23',
  '2026-07-24'
];

function detectDatesheetConflicts(entries) {
  const conflicts = [];
  for (let i = 0; i < entries.length; i++) {
    for (let j = i + 1; j < entries.length; j++) {
      const e1 = entries[i];
      const e2 = entries[j];
      if (e1.date === e2.date && e1.examSlot === e2.examSlot) {
        const id1 = e1._id || e1.id;
        const id2 = e2._id || e2.id;
        if (e1.room === e2.room) conflicts.push({ type: 'ROOM_OVERLAP', description: `Room clash in ${e1.room}: Exam for ${e1.courseCode} and ${e2.courseCode} are both assigned here.`, cellIds: [id1, id2] });
        if (e1.invigilator && e2.invigilator && e1.invigilator === e2.invigilator) conflicts.push({ type: 'INVIGILATOR_OVERLAP', description: `Invigilator clash: ${e1.invigilator} assigned to both ${e1.courseCode} and ${e2.courseCode}.`, cellIds: [id1, id2] });
        if (e1.batch === e2.batch && e1.semester === e2.semester) conflicts.push({ type: 'COHORT_OVERLAP', description: `Cohort clash: Batch ${e1.batch} (Sem ${e1.semester}) has exams for ${e1.courseCode} and ${e2.courseCode} at same time.`, cellIds: [id1, id2] });
      }
    }
  }
  return conflicts;
}

const COLORS = ['#3B82F6', '#8B5CF6', '#F59E0B', '#10B981', '#EC4899', '#6366F1'];

export default function DatesheetGenerator({ setActiveNav }) {
  const { user } = useAuth();
  const { showAlert } = useModal();
  const [entries, setEntries] = useState([]);
  const [conflicts, setConflicts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [batches, setBatches] = useState([]);

  // Filters
  const [selectedDept, setSelectedDept] = useState("Computer Science");
  const [selectedProgram, setSelectedProgram] = useState("BS Computer Science");
  const [selectedBatchId, setSelectedBatchId] = useState("");
  const [selectedSemester, setSelectedSemester] = useState("");
  const [selectedSection, setSelectedSection] = useState("Section A");
  const [timingPage, setTimingPage] = useState(1);
  const timingLimit = 5;
  const [clashPage, setClashPage] = useState(1);
  const clashLimit = 5;

  useEffect(() => {
    fetchMetadataAndDatesheet();
  }, []);

  const fetchMetadataAndDatesheet = async () => {
    setLoading(true);
    try {
      const batchesRes = await fetch("/api/batches");
      if (batchesRes.ok) {
        const batchesData = await batchesRes.json();
        setBatches(batchesData.data || []);
        // Only pick a default batch/semester on first load - on later refetches (e.g. after
        // compiling), keep whatever the user currently has selected instead of snapping back.
        if (batchesData.data?.length > 0 && !selectedBatchId) {
          setSelectedBatchId(batchesData.data[0]._id);
          setSelectedSemester(batchesData.data[0].semester || "6");
        }
      }

      const dateRes = await fetch("/api/scheduling/datesheet");
      if (dateRes.ok) {
        const dateData = await dateRes.json();
        const data = dateData.data?.entries || [];
        setEntries(data);
        setConflicts(detectDatesheetConflicts(data));
      }
    } catch (err) {
      console.error("Failed to load:", err);
    } finally {
      setLoading(false);
    }
  };

  const handleCompile = async () => {
    if (!selectedBatchId || !selectedSemester) return;
    setGenerating(true);
    try {
      const token = localStorage.getItem("token");
      const authHeaders = { "Authorization": `Bearer ${token}` };

      // Generation and constraint checking now happen server-side (autoGenerateDatesheet),
      // mirroring how the Timetable Generator calls /api/scheduling/auto-generate. This keeps
      // the datesheet engine backend-driven, persisted, and audit-logged instead of building
      // and saving entries purely on the client.
      const saveRes = await fetch("/api/scheduling/datesheet/auto-generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...authHeaders
        },
        body: JSON.stringify({ batchId: selectedBatchId, semester: selectedSemester })
      });

      if (saveRes.ok) {
        const saveResult = await saveRes.json();
        if (saveResult.status === 'partial' && Array.isArray(saveResult.data?.unscheduledCourses) && saveResult.data.unscheduledCourses.length > 0) {
          showAlert(
            'Datesheet Partially Generated',
            `${saveResult.message} Unscheduled: ${saveResult.data.unscheduledCourses.join(', ')}`
          );
        }
        // Refetch the full dataset (all batches/semesters) rather than replacing `entries` with
        // just this response's rows - otherwise switching to a different, previously-generated
        // semester afterward shows nothing until a full page reload.
        await fetchMetadataAndDatesheet();
      } else {
        const errResult = await saveRes.json().catch(() => ({}));
        console.error("Datesheet generation failed:", errResult.message);
        showAlert(
          'Datesheet Generation Failed',
          errResult.message || 'Could not generate the datesheet for this batch/semester. Check that the active curriculum has courses tagged for this semester.'
        );
      }
    } catch (err) {
      console.error("Failed to compile:", err);
      showAlert('Datesheet Generation Failed', 'A network or server error occurred while generating the datesheet.');
    } finally {
      setGenerating(false);
    }
  };

  const handleExportDatesheet = () => {
    if (!entries || entries.length === 0) {
      alert('No datesheet records available to export.');
      return;
    }

    const headers = ['Date', 'Exam Slot', 'Course Code', 'Course Name', 'Room', 'Invigilator', 'Batch'];
    const rows = entries.map(e => [
      e.date,
      e.examSlot,
      e.courseCode,
      e.courseName,
      e.room,
      e.invigilator || 'TBD',
      e.batch
    ]);

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(val => {
        const cell = val === null || val === undefined ? '' : String(val);
        return cell.includes(',') || cell.includes('"') ? `"${cell.replace(/"/g, '""')}"` : cell;
      }).join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `Exam_Datesheet_${new Date().toISOString().split('T')[0]}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // --- Dynamic Metrics ---
  const filteredEntries = entries.filter(e => {
    const batchMatch = !selectedBatchId || e.batch === batches.find(b => b._id === selectedBatchId)?.code;
    const semesterMatch = !selectedSemester || String(e.semester) === String(selectedSemester);
    return batchMatch && semesterMatch;
  });
  const totalExams = filteredEntries.length;
  const totalCourses = new Set(filteredEntries.map(e => e.courseCode)).size;
  const totalInvigilators = new Set(filteredEntries.filter(e => e.invigilator).map(e => e.invigilator)).size;
  const totalRooms = new Set(filteredEntries.filter(e => e.room).map(e => e.room)).size;

  // --- Room Utilization Donut Chart Data ---
  const roomCounts = {};
  filteredEntries.forEach(e => {
    if (e.room) roomCounts[e.room] = (roomCounts[e.room] || 0) + 1;
  });
  const roomData = Object.entries(roomCounts)
    .sort((a, b) => b[1] - a[1])
    .map(([name, value]) => ({ name, value }));

  // --- Exam Timing Details Aggregation ---
  const timingDetails = [];
  filteredEntries.forEach(e => {
    timingDetails.push({
      code: e.courseCode,
      title: e.courseName,
      date: formatDate(e.date),
      slot: e.examSlot,
      invigilator: e.invigilator,
      room: e.room,
      batch: e.batch
    });
  });

  const getSlotColor = (courseName, room) => {
    if (room?.toLowerCase().includes('hall')) return 'bg-purple-50 border-purple-100 border-l-purple-500 text-purple-900';
    if (courseName?.includes('Database') || courseName?.includes('Software')) return 'bg-emerald-50 border-emerald-100 border-l-emerald-500 text-emerald-900';
    if (courseName?.includes('AI') || courseName?.includes('Artificial')) return 'bg-pink-50 border-pink-100 border-l-pink-500 text-pink-900';
    if (courseName?.includes('Operating')) return 'bg-amber-50 border-amber-100 border-l-amber-500 text-amber-900';
    return 'bg-indigo-50 border-indigo-100 border-l-indigo-500 text-indigo-900';
  };

  function formatDate(dateStr) {
    const options = { weekday: 'short', month: 'short', day: 'numeric' };
    return new Date(dateStr).toLocaleDateString('en-US', options);
  }

  const selectedBatchObj = batches.find(b => b._id === selectedBatchId);
  const batchLabel = selectedBatchObj ? `${selectedBatchObj.code} (${selectedBatchObj.semester === 6 ? '2023 Spring' : '2024'})` : '23S (2023 Spring)';

  // Grid dates should reflect whatever dates the actual scheduled exams fall on
  // (the backend generates a rolling "next 10 weekdays from today" window, so a
  // fixed hardcoded date list quickly goes stale). Fall back to the static DATES
  // list only when there's no data to derive dates from yet.
  const gridDates = filteredEntries.length > 0
    ? [...new Set(filteredEntries.map(e => e.date))].sort()
    : DATES;

  if (loading) {
    return <div className="p-8 text-center text-slate-500 font-semibold animate-pulse">Loading Exam Management...</div>;
  }

  return (
    <div className="bg-slate-50 min-h-screen text-slate-800 p-4 sm:p-6 pb-20 font-sans max-w-full overflow-x-hidden">

      {/* Top Filter Bar */}
      <div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-sm mb-6">
        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-4">
          <div className="flex flex-col gap-1 w-full">
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wide">Department</label>
            <div className="relative">
              <select className="w-full appearance-none bg-slate-50 border border-slate-200 text-xs font-bold text-slate-700 py-2 px-3 rounded-lg outline-none cursor-pointer">
                <option>Computer Science</option>
              </select>
              <ChevronDown className="w-3.5 h-3.5 text-slate-400 absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" />
            </div>
          </div>
          <div className="flex flex-col gap-1 w-full">
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wide">Program</label>
            <div className="relative">
              <select className="w-full appearance-none bg-slate-50 border border-slate-200 text-xs font-bold text-slate-700 py-2 px-3 rounded-lg outline-none cursor-pointer">
                <option>BS Computer Science</option>
              </select>
              <ChevronDown className="w-3.5 h-3.5 text-slate-400 absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" />
            </div>
          </div>
          <div className="flex flex-col gap-1 w-full">
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wide">Batch (Year-Term)</label>
            <div className="relative">
              <select
                value={selectedBatchId}
                onChange={e => setSelectedBatchId(e.target.value)}
                className="w-full appearance-none bg-slate-50 border border-slate-200 text-xs font-bold text-slate-700 py-2 px-3 rounded-lg outline-none cursor-pointer"
              >
                {batches.map(b => <option key={b._id} value={b._id}>{b.code} ({b.startYear || 2024})</option>)}

              </select>
              <ChevronDown className="w-3.5 h-3.5 text-slate-400 absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" />
            </div>
          </div>
          <div className="flex flex-col gap-1 w-full">
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wide">Semester</label>
            <ResponsiveSelect
              value={selectedSemester}
              onChange={e => setSelectedSemester(e.target.value)}
              placeholder="All Semesters"
              label="Select Semester"
              className="w-full"
              options={[
                { value: '', label: 'All Semesters' },
                ...[1, 2, 3, 4, 5, 6, 7, 8].map(s => ({ value: s, label: `Semester ${s}` }))
              ]}
            />
          </div>
        </div>
        <div className="flex justify-end gap-2 pt-4 border-t border-slate-100">
          <button
            onClick={handleCompile}
            disabled={generating}
            style={{
              display: 'flex', alignItems: 'center', gap: '8px',
              padding: '10px 18px',
              background: 'linear-gradient(135deg, #2563EB 0%, #1D4ED8 100%)', color: '#fff',
              border: 'none', borderRadius: '10px',
              fontSize: '13px', fontWeight: 700, cursor: generating ? 'not-allowed' : 'pointer',
              opacity: generating ? 0.7 : 1,
              boxShadow: '0 4px 12px rgba(37,99,235,0.2)',
              transition: 'all 0.15s ease'
            }}
            onMouseEnter={e => { if (!generating) { e.currentTarget.style.transform = 'translateY(-1px)'; e.currentTarget.style.boxShadow = '0 6px 16px rgba(37,99,235,0.3)'; } }}
            onMouseLeave={e => { if (!generating) { e.currentTarget.style.transform = 'none'; e.currentTarget.style.boxShadow = '0 4px 12px rgba(37,99,235,0.2)'; } }}
          >
            <RefreshCw size={15} className={generating ? 'animate-spin' : ''} />
            {generating ? 'Processing...' : 'Compile Datesheet'}
          </button>
          <button
            onClick={handleExportDatesheet}
            style={{
              display: 'flex', alignItems: 'center', gap: '8px',
              padding: '10px 18px',
              backgroundColor: '#EFF6FF', color: '#2563EB',
              border: '1px solid #BFDBFE', borderRadius: '10px',
              fontSize: '13px', fontWeight: 700, cursor: 'pointer',
              transition: 'all 0.15s ease'
            }}
            onMouseEnter={e => { e.currentTarget.style.backgroundColor = '#2563EB'; e.currentTarget.style.color = '#fff'; }}
            onMouseLeave={e => { e.currentTarget.style.backgroundColor = '#EFF6FF'; e.currentTarget.style.color = '#2563EB'; }}
          >
            <Download size={15} /> Export Datesheet
          </button>
        </div>
      </div>

      <div className="space-y-6">

        {/* Main Grid Card */}
        <div className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden flex flex-col">
          <div className="px-5 py-4 border-b border-slate-100 flex flex-col md:flex-row justify-between items-start md:items-center gap-3 bg-white">
            <div className="flex items-center gap-3">
              <h3 className="text-sm font-extrabold text-slate-800">Final Exams Datesheet - BSCS {batchLabel} - Semester {selectedSemester || 6}</h3>
              {filteredEntries.length > 0 ? (
                <span className="px-2 py-0.5 bg-emerald-100 text-emerald-700 text-[10px] font-bold uppercase tracking-wider rounded border border-emerald-200">Published</span>
              ) : (
                <span className="px-2 py-0.5 bg-slate-100 text-slate-500 text-[10px] font-bold uppercase tracking-wider rounded border border-slate-200">Not Generated</span>
              )}
            </div>
            <div className="flex items-center gap-3">
              <button
                onClick={() => setActiveNav && setActiveNav('schedule_override')}
                className="px-4 py-2 bg-brandAccent text-white text-xs font-bold rounded-lg shadow-sm hover:bg-blue-600 transition-colors"
              >
                Edit Datesheet
              </button>
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse min-w-[900px]">
              <thead>
                <tr className="bg-slate-50/50 text-slate-500 text-[11px] font-bold uppercase tracking-wider border-b border-slate-200">
                  <th className="px-4 py-3 w-36 text-center border-r border-slate-100 sticky left-0 bg-slate-50 z-10 shadow-[1px_0_0_0_#f1f5f9]">Date</th>
                  {EXAMSLOTS.map(slot => <th key={slot} className="px-4 py-3 text-center border-r border-slate-100 w-64">{slot}</th>)}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-xs">
                {gridDates.map(date => (
                  <tr key={date} className="hover:bg-slate-50/30 transition-colors">
                    <td className="px-4 py-5 text-center font-bold text-slate-600 border-r border-slate-100 align-middle bg-slate-50 sticky left-0 z-10 shadow-[1px_0_0_0_#f1f5f9]">
                      <div className="flex flex-col items-center gap-1">
                        <Calendar className="w-4 h-4 text-slate-400" />
                        <span className="whitespace-nowrap">{formatDate(date)}</span>
                      </div>
                    </td>
                    {EXAMSLOTS.map(slot => {
                      const cellEntries = filteredEntries.filter(e => e.date === date && e.examSlot === slot);
                      return (
                        <td key={slot} className="p-2 border-r border-slate-100 align-top h-auto min-h-[7rem]">
                          {cellEntries.map((entry, i) => (
                            <div key={i} className={`p-2.5 rounded-lg border border-l-4 ${getSlotColor(entry.courseName, entry.room)} mb-2 flex flex-col text-left shadow-sm transition-all hover:shadow-md h-full min-h-[5rem] relative overflow-hidden group`}>
                              <div className="absolute top-0 left-0 w-1 h-full bg-current opacity-20 group-hover:opacity-50 transition-opacity" />
                              <span className="font-bold text-[11px] leading-tight mb-1">{entry.courseCode} - {entry.courseName}</span>
                              <div className="mt-auto flex flex-col gap-0.5">
                                <span className="font-semibold text-[10px] opacity-80 w-full truncate" title={entry.invigilator}>{entry.invigilator}</span>
                                <span className="font-bold text-[10px]">{entry.room}</span>
                              </div>
                            </div>
                          ))}
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div className="flex flex-col gap-6">
          {/* Bottom Table: Exam Schedule Details */}
          <div className="bg-white border border-slate-200 rounded-2xl shadow-sm p-5 overflow-hidden min-w-0">
            <h3 className="text-sm font-bold text-slate-800 mb-4">Exam Schedule Details</h3>
            <div className="overflow-x-auto rounded-xl border border-slate-200">
              <table className="w-full text-left text-xs min-w-[700px]">
                <thead className="bg-slate-50 text-slate-500 font-bold uppercase text-[10px] tracking-wider border-b border-slate-200">
                  <tr>
                    <th className="px-4 py-3">Code</th>
                    <th className="px-4 py-3">Course Title</th>
                    <th className="px-4 py-3">Date</th>
                    <th className="px-4 py-3">Time Slot</th>
                    <th className="px-4 py-3">Invigilator</th>
                    <th className="px-4 py-3">Room</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 font-medium">
                  {timingDetails.length > 0 ? (() => {
                    const currentTimingDetails = timingDetails.slice(
                      (timingPage - 1) * timingLimit,
                      timingPage * timingLimit
                    );
                    return currentTimingDetails.map((td, i) => (
                      <tr key={i} className="hover:bg-slate-50/50 transition-colors">
                        <td className="px-4 py-3 text-slate-800 font-bold">{td.code}</td>
                        <td className="px-4 py-3 text-slate-600">{td.title}</td>
                        <td className="px-4 py-3 text-brandNavy font-bold">{td.date}</td>
                        <td className="px-4 py-3 text-slate-500">{td.slot}</td>
                        <td className="px-4 py-3 text-slate-800">{td.invigilator}</td>
                        <td className="px-4 py-3 text-emerald-700 font-bold">{td.room}</td>
                      </tr>
                    ));
                  })() : (
                    <tr><td colSpan={6} className="px-4 py-8 text-center text-slate-400">No exams scheduled</td></tr>
                  )}
                </tbody>
              </table>
            </div>
            {timingDetails.length > 0 && (
              <div className="flex justify-between items-center mt-4 text-xs">
                <span className="text-slate-500 font-medium">
                  Showing {(timingPage - 1) * timingLimit + 1}–{Math.min(timingPage * timingLimit, timingDetails.length)} of {timingDetails.length} exams
                </span>
                <div className="flex gap-1.5">
                  {Array.from({ length: Math.ceil(timingDetails.length / timingLimit) }, (_, idx) => idx + 1).map(p => (
                    <button
                      key={p}
                      onClick={() => setTimingPage(p)}
                      className={`px-2.5 py-1 rounded-md font-bold transition-all ${timingPage === p ? 'bg-brandAccent text-white shadow-sm' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}
                    >
                      {p}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Bottom Panel: Clash Check */}
          <div className="bg-white border border-slate-200 rounded-2xl shadow-sm p-5 flex flex-col min-w-0">
            <h3 className="text-sm font-bold text-slate-800 mb-4">Datesheet Clash Check</h3>

            {conflicts.length === 0 ? (
              <div className="flex-1 bg-emerald-50/50 border border-emerald-100 rounded-xl p-6 flex flex-col items-center justify-center text-center">
                <div className="w-12 h-12 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mb-3">
                  <CheckCircle2 className="w-6 h-6" />
                </div>
                <h4 className="text-sm font-extrabold text-emerald-700 mb-1">No Clashes Found!</h4>
                <p className="text-xs text-emerald-600/80 font-medium">Great! There are no faculty, room or cohort overlaps in this datesheet.</p>
              </div>
            ) : (
              <div className="flex-1 bg-rose-50/50 border border-rose-100 rounded-xl p-5 flex flex-col">
                <div className="flex items-center gap-2 mb-3 text-rose-700">
                  <AlertTriangle className="w-5 h-5" />
                  <h4 className="text-sm font-extrabold">Clashes Detected ({conflicts.length})</h4>
                </div>
                <ul className="space-y-2 pr-1 mb-3">
                  {(() => {
                    const currentConflicts = conflicts.slice((clashPage - 1) * clashLimit, clashPage * clashLimit);
                    return currentConflicts.map((c, i) => (
                      <li key={i} className="text-[11px] p-2 bg-white rounded border border-rose-100 text-rose-800 shadow-sm">
                        <strong className="block text-[10px] uppercase font-bold text-rose-500 mb-0.5">{c.type}</strong>
                        {c.description}
                      </li>
                    ));
                  })()}
                </ul>
                {conflicts.length > clashLimit && (
                  <div className="flex justify-between items-center mt-auto text-xs border-t border-rose-100 pt-3">
                    <span className="text-rose-600/80 font-medium">
                      Showing {(clashPage - 1) * clashLimit + 1}–{Math.min(clashPage * clashLimit, conflicts.length)} of {conflicts.length}
                    </span>
                    <div className="flex gap-1.5">
                      {Array.from({ length: Math.ceil(conflicts.length / clashLimit) }, (_, idx) => idx + 1).map(p => (
                        <button
                          key={p}
                          onClick={() => setClashPage(p)}
                          className={`px-2 py-0.5 rounded text-[10px] font-bold transition-all ${clashPage === p ? 'bg-rose-500 text-white' : 'bg-white text-rose-600 border border-rose-200 hover:bg-rose-50'}`}
                        >
                          {p}
                        </button>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>

        {/* Summary Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

          {/* Exam Summary */}
          <div className="bg-white border border-slate-200 rounded-2xl shadow-sm p-5">
            <h3 className="text-sm font-bold text-slate-800 mb-4">Exam Summary</h3>
            <div className="space-y-3">
              <div className="flex justify-between items-center p-2.5 rounded-lg hover:bg-slate-50 transition-colors">
                <div className="flex items-center gap-2.5 text-slate-600 text-xs font-bold">
                  <LayoutGrid className="w-4 h-4 text-brandAccent" /> Total Exams
                </div>
                <span className="text-sm font-extrabold text-slate-800">{totalExams}</span>
              </div>
              <div className="flex justify-between items-center p-2.5 rounded-lg hover:bg-slate-50 transition-colors">
                <div className="flex items-center gap-2.5 text-slate-600 text-xs font-bold">
                  <BookOpen className="w-4 h-4 text-emerald-500" /> Total Courses
                </div>
                <span className="text-sm font-extrabold text-slate-800">{totalCourses}</span>
              </div>
              <div className="flex justify-between items-center p-2.5 rounded-lg hover:bg-slate-50 transition-colors">
                <div className="flex items-center gap-2.5 text-slate-600 text-xs font-bold">
                  <Users className="w-4 h-4 text-purple-500" /> Total Invigilators
                </div>
                <span className="text-sm font-extrabold text-slate-800">{totalInvigilators}</span>
              </div>
              <div className="flex justify-between items-center p-2.5 rounded-lg hover:bg-slate-50 transition-colors">
                <div className="flex items-center gap-2.5 text-slate-600 text-xs font-bold">
                  <Home className="w-4 h-4 text-amber-500" /> Exam Halls Used
                </div>
                <span className="text-sm font-extrabold text-slate-800">{totalRooms}</span>
              </div>
            </div>
          </div>

          {/* Room Utilization Donut Chart */}
          <div className="bg-white border border-slate-200 rounded-2xl shadow-sm p-5">
            <h3 className="text-sm font-bold text-slate-800 mb-4">Exam Hall Utilization</h3>
            {roomData.length > 0 ? (
              <>
                <div className="h-40 w-full relative">
                  <ResponsiveContainer width="100%" height="100%">
                    <PieChart>
                      <Pie
                        data={roomData}
                        cx="50%" cy="50%"
                        innerRadius={50} outerRadius={70}
                        paddingAngle={3}
                        dataKey="value"
                        stroke="none"
                      >
                        {roomData.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                        ))}
                      </Pie>
                      <Tooltip formatter={(val) => [`${val} exams`, 'Usage']} contentStyle={{ borderRadius: '8px', border: '1px solid #E2E8F0', fontSize: '11px', fontWeight: 'bold' }} />
                    </PieChart>
                  </ResponsiveContainer>
                  {/* Center Text */}
                  <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
                    <span className="text-lg font-extrabold text-slate-800">{filteredEntries.length}</span>
                    <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Exams</span>
                  </div>
                </div>
                <div className="mt-4 grid grid-cols-2 gap-y-2 gap-x-1">
                  {roomData.map((entry, i) => (
                    <div key={i} className="flex items-center gap-1.5 text-[10px] font-bold text-slate-600">
                      <div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: COLORS[i % COLORS.length] }} />
                      <span className="truncate max-w-[70px]" title={entry.name}>{entry.name}</span>
                      <span className="text-slate-400 ml-auto">{Math.round((entry.value / filteredEntries.length) * 100)}%</span>
                    </div>
                  ))}
                </div>
              </>
            ) : (
              <div className="h-32 flex items-center justify-center text-xs text-slate-400">No room data available</div>
            )}
          </div>



          {/* Exam Info */}
          <div className="bg-slate-50 border border-slate-200 rounded-2xl shadow-sm p-5">
            <h3 className="text-sm font-bold text-slate-800 mb-4">Exam Info</h3>
            <div className="space-y-3 text-xs">
              <div className="flex justify-between">
                <span className="text-slate-500 font-medium">Batch (Year-Term):</span>
                <span className="font-bold text-slate-800">{selectedBatchObj?.code || '23S'} (2023 Spring)</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500 font-medium">Program:</span>
                <span className="font-bold text-slate-800">BS Computer Science</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500 font-medium">Semester:</span>
                <span className="font-bold text-slate-800">Semester {selectedSemester || 6}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500 font-medium">Exam Period:</span>
                <span className="font-bold text-brandNavy">Jul 13 - Jul 24</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}