import express from 'express';
import {
  getTimetable,
  saveTimetable,
  getDatesheet,
  saveDatesheet,
  saveOverride,
  checkTimetableClash,
  autoGenerateTimetable,
  autoGenerateDatesheet,
  validateRoomCapacity
} from '../controllers/schedulingController.js';
import { protect } from '../middleware/authMiddleware.js';
import { restrictTo } from '../middleware/roleMiddleware.js';

const router = express.Router();

router.use(protect);

// Read schedules is accessible by all authenticated roles (Advisors, HODs, Admins)
router.get('/timetable', getTimetable);
router.get('/datesheet', getDatesheet);
router.post('/timetable/check-clash', checkTimetableClash);
router.post('/auto-generate', restrictTo('academic_admin', 'dean'), autoGenerateTimetable);
router.post('/datesheet/auto-generate', restrictTo('academic_admin', 'dean'), autoGenerateDatesheet);
router.post('/validate-capacity', validateRoomCapacity);

// Writing/Mutating schedules requires academic admin or dean privileges
router.post('/timetable', restrictTo('academic_admin', 'dean'), saveTimetable);
router.post('/datesheet', restrictTo('academic_admin', 'dean'), saveDatesheet);
router.post('/override', restrictTo('academic_admin', 'dean'), saveOverride);

export default router;
